/**
 * Textes de la page d'accueil, en francais et en arabe tunisien.
 *
 * Toute chaine affichee sur la landing vit ici : le composant ne contient
 * aucun texte en dur, ce qui permet de basculer la langue sans le toucher et
 * de relire la copie sans lire du JSX.
 */

export const CONTENU = {
  fr: {
  nav1: "Fonctionnalités",
    nav2: "Pourquoi Salonista",
    nav3: "Tarifs",
    nav4: "FAQ",
    cta: "Commencer gratuitement",
    eyebrow: "Caisse pour salons de beauté · Tunisie",
    h1a: "Le nouveau standard",
    h1b: "pour gérer votre salon.",
    cta2: "Découvrir Salonista",
    hf1: "Aucune carte bancaire",
    hf2: "Prête en cinq minutes",
    hf3: "Fonctionne sans internet",
    chip1: "Encaissement",
    chip2: "Coupe femme",
    chip3: "Brushing",
    chip4: "Total",
    chip5: "Encaissé",
    e1: "La caisse",
    h2a: "Tout ce dont votre salon a besoin.",
    h2b: "Au même endroit.",
    c1: "Encaissement",
    c2: "Agenda",
    c3: "Clientes",
    c4: "Services",
    c5: "Produits",
    c6: "Stock",
    c7: "Statistiques",
    c8: "Historique des ventes",
    e2: "Le cœur du salon",
    h3a: "Plus qu'une caisse.",
    h3b: "Le cœur de votre salon.",
    p3: "Vos rendez-vous, vos prestations, vos clientes et vos ventes réunis dans un seul écran — pensé pour le comptoir d'un salon, pas pour un bureau.",
    fig1: "Pour commencer",
    fig2: "Pour démarrer",
    fig3: "Vos données accessibles",
    fig4: "Pensé pour les salons",
    e3: "Ce qu'elle sait faire",
    h4a: "Six gestes du",
    h4b: "quotidien.",
    l1: "Encaissement",
    s1: "Encaissez en quelques secondes.",
    l2: "Agenda",
    s2: "Ne manquez plus jamais un rendez-vous.",
    l3: "Clientes",
    s3: "Connaissez mieux vos clientes.",
    l4: "Stock",
    s4: "Gardez votre stock sous contrôle.",
    l5: "Statistiques",
    s5: "Comprenez ce qui fait grandir votre salon.",
    l6: "Hors connexion",
    s6: "Votre caisse fonctionne même sans internet.",
    h5a: "Vous prenez soin de vos clientes.",
    h5b: "Nous nous occupons du reste.",
    e4: "La différence",
    h6a: "Le même salon,",
    h6b: "deux journées.",
    apres: "Avec Salonista",
    apresT: "Tout se tient.",
    ap1: "Une caisse centralisée",
    ap2: "L'agenda dans la caisse",
    ap3: "Chaque cliente reconnue",
    ap4: "Le stock à jour tout seul",
    ap5: "Les chiffres du jour, en un coup d'œil",
    ap6: "Une gestion simplifiée",
    avant: "Avant Salonista",
    avantT: "Tout est éparpillé.",
    av1: "Des cahiers",
    av2: "Des calculs à la main",
    av3: "Des rendez-vous dispersés",
    av4: "Un stock difficile à suivre",
    av5: "Aucune visibilité sur l'activité",
    av6: "Du temps perdu chaque soir",
    hint: "Faites glisser pour comparer",
    e5: "Pourquoi Salonista",
    h7a: "Pensé pour les salons.",
    h7b: "Conçu pour évoluer avec vous.",
    w1: "Simple à utiliser",
    w2: "Sans carte bancaire pour commencer",
    w3: "Prête en quelques minutes",
    w4: "Fonctionne sans internet",
    w5: "Adaptée au marché tunisien",
    w6: "Interface moderne",
    w7: "Gestion centralisée",
    e6: "Questions",
    h8: "Ce qu'on nous demande",
    q1: "Il me faut quel matériel ?",
    a1: "Un ordinateur, une tablette ou un téléphone avec un navigateur récent. Une imprimante thermique 80 mm si vous voulez des tickets papier — sinon le ticket reste à l'écran.",
    q2: "Et si internet coupe ?",
    a2: "La caisse continue et garde les ventes sur l'appareil. Dès que la connexion revient, tout remonte automatiquement.",
    q3: "Mes employées verront-elles mon chiffre d'affaires ?",
    a3: "Seulement si vous le décidez. Chaque employée entre par son code, avec les droits que vous lui donnez.",
    q4: "Est-ce que ça restera gratuit ?",
    a4: "La caisse est gratuite aujourd'hui, sans limite de ventes. Les salons inscrits pendant cette phase gardent l'accès gratuit.",
    h9a: "Votre salon mérite mieux",
    h9b: "qu'une simple caisse.",
    p9: "Commencez gratuitement aujourd'hui.",
    cta3: "Démarrer ma caisse gratuitement",
    fine: "Aucune carte bancaire requise",
    foot: "Caisse pour salons de beauté · Tunisie",
    deja: "J'ai déjà un compte",
  },
  ar: {
  nav1: "الخدمات",
    nav2: "علاش سالونيستا",
    nav3: "الأثمنة",
    nav4: "أسئلة",
    cta: "ابدأ مجانا",
    cta2: "اكتشف سالونيستا",
    cta3: "ابدأ الكاس متاعي مجانا",
    eyebrow: "كاس لصالونات التجميل · تونس",
    h1a: "المعيار الجديد",
    h1b: "لتسيير صالونك.",
    hf1: "بلا كارط بنكية",
    hf2: "جاهزة في خمس دقايق",
    hf3: "تخدم بلا أنترنات",
    chip1: "خلاص",
    chip2: "قص شعر",
    chip3: "بروشينغ",
    chip4: "الجملة",
    chip5: "تخلّص",
    e1: "الكاس",
    h2a: "كل ما يلزم صالونك.",
    h2b: "في بلاصة وحدة.",
    c1: "الخلاص",
    c2: "المواعيد",
    c3: "الحرفاء",
    c4: "الخدمات",
    c5: "المنتوجات",
    c6: "الستوك",
    c7: "الإحصائيات",
    c8: "تاريخ المبيعات",
    e2: "قلب الصالون",
    h3a: "أكثر من كاس.",
    h3b: "قلب صالونك.",
    p3: "مواعيدك، خدماتك، حرفاؤك ومبيعاتك في شاشة وحدة — مصمّمة لكونتوار صالون، موش لمكتب.",
    fig1: "باش تبدا",
    fig2: "باش تنطلق",
    fig3: "معطياتك موجودة",
    fig4: "مصمّمة للصالونات",
    e3: "شنوّة تنجم تعمل",
    h4a: "ستة حركات",
    h4b: "كل يوم.",
    l1: "الخلاص",
    s1: "خلّص في ثواني.",
    l2: "المواعيد",
    s2: "ما يفوتك حتى موعد.",
    l3: "الحرفاء",
    s3: "اعرف حرفاءك أكثر.",
    l4: "الستوك",
    s4: "ستوكك تحت عينك.",
    l5: "الإحصائيات",
    s5: "افهم شنوّة يكبّر صالونك.",
    l6: "بلا أنترنات",
    s6: "الكاس تخدم حتى بلا أنترنات.",
    h5a: "انت تعتني بحرفاءك.",
    h5b: "واحنا نتكفّلو بالباقي.",
    e4: "الفرق",
    h6a: "نفس الصالون،",
    h6b: "نهارين مختلفين.",
    avant: "قبل سالونيستا",
    avantT: "كل شي مشتّت.",
    av1: "كراريس",
    av2: "حساب باليد",
    av3: "مواعيد مشتّتة",
    av4: "ستوك صعيب تتبّعو",
    av5: "ما تعرفش وين واصل",
    av6: "وقت ضايع كل ليلة",
    apres: "مع سالونيستا",
    apresT: "كل شي في بلاصتو.",
    ap1: "كاس مركزية",
    ap2: "المواعيد في الكاس",
    ap3: "كل حريفة معروفة",
    ap4: "الستوك يتحيّن وحدو",
    ap5: "أرقام النهار في نظرة",
    ap6: "تسيير مبسّط",
    hint: "جرّ باش تقارن",
    e5: "علاش سالونيستا",
    h7a: "مصمّمة للصالونات.",
    h7b: "وتكبر معاك.",
    w1: "ساهلة للاستعمال",
    w2: "بلا كارط بنكية باش تبدا",
    w3: "جاهزة في دقايق",
    w4: "تخدم بلا أنترنات",
    w5: "مناسبة للسوق التونسية",
    w6: "واجهة عصرية",
    w7: "تسيير مركزي",
    e6: "أسئلة",
    h8: "اللي يسألونا عليه",
    q1: "شنوّة يلزمني من معدات ؟",
    a1: "كمبيوتر، تابليت ولا تليفون بنافيغاتور جديد. وطابعة حرارية 80 مم كان تحب تيكي بالورقة — وإلا التيكي يبقى في الشاشة.",
    q2: "وكان تقطع الأنترنات ؟",
    a2: "الكاس تكمّل تخدم وتحفظ المبيعات في الجهاز. وكي ترجع الأنترنات، كل شي يطلع وحدو.",
    q3: "عاملاتي باش يشوفو رقم معاملاتي ؟",
    a3: "كان انت تحب برك. كل عاملة تدخل بالكود متاعها، بالحقوق اللي تعطيها انت.",
    q4: "باش تبقى مجانية ؟",
    a4: "الكاس مجانية اليوم، بلا حد للمبيعات. الصالونات اللي تسجّل في هالمرحلة تحافظ على المجانية.",
    h9a: "صالونك يستاهل أكثر",
    h9b: "من كاس عادية.",
    p9: "ابدأ مجانا اليوم.",
    fine: "بلا كارط بنكية",
    foot: "كاس لصالونات التجميل · تونس",
    deja: "عندي كونط",
  },
} as const;

export type Langue = keyof typeof CONTENU;
export type Textes = (typeof CONTENU)["fr"];
