/**
 * Textes de la page d'accueil, en francais et en arabe tunisien.
 *
 * Toute chaine affichee sur la landing vit ici : le composant ne contient
 * aucun texte en dur, ce qui permet de basculer la langue sans le toucher et
 * de relire la copie sans lire du JSX.
 */

export const CONTENU = {
  fr: {
  nav1: "Fonctionnalités",
    nav2: "Pourquoi Salonista",
    nav3: "Tarifs",
    nav4: "FAQ",
    cta: "Commencer gratuitement",
    eyebrow: "Offre de lancement · 100% gratuite",
    // Le titre tient en TROIS lignes courtes : chacune se lit d'un coup
    // d'oeil, et la derniere porte la promesse.
    h1a: "Votre caisse digitale.",
    h1b: "Votre salon.",
    h1c: "Plus simplement.",
    cta2: "Découvrir Salonista",
    // Les quatre benefices, en grille sous la phrase d'accroche.
    b1: "Caisse digitale pour salons de beauté",
    b2: "100% gratuite",
    b3: "Téléphone · Tablette · PC",
    b4: "Ventes & prestations",
    // Une seule phrase sous le titre : ce que fait le produit, pour qui.
    // NE PAS y remettre « sans internet » : la caisse en a besoin.
    heroLede:
      "Gérez vos ventes, suivez votre chiffre d'affaires et gardez le contrôle de votre salon depuis votre téléphone, tablette ou PC.",
    // Decrit la photo pour qui ne la voit pas : un lecteur d'ecran doit
    // apprendre ce que montre l'image, pas entendre « image ».
    altHero:
      "Au comptoir d'un salon, une employée présente la caisse Salonista sur une tablette : la grille des services avec leurs prix, et le panier en cours.",
    e1: "L'essentiel, bien pensé",
    h2a: "Une caisse pensée",
    h2b: "pour votre salon.",
    // Une seule phrase, pas une liste : les quatre cartes portent deja le
    // detail. Reprend le ton du reste de la landing plutot que de repeter
    // « caisse pour salons de beaute », deja dans l'eyebrow du hero.
    h2lede:
      "Salonista est une caisse digitale simple, conçue spécialement pour les professionnels de la beauté.",
    // Quatre cartes en apercu, comme un menu qu'on feuillette avant d'ouvrir
    // le produit : chacune montre un bout d'ecran REEL, jamais l'ecran
    // entier — le detail se decouvre en activant sa caisse gratuite, pas ici.
    tzLabel1: "Caisse",
    tzTitre1: "Encaissez simplement",
    tzTexte1: "Enregistrez vos ventes et prestations rapidement.",
    tzAlt1:
      "Un apercu de l'ecran d'encaissement : la grille des services du salon et le debut du panier.",
    tzLabel2: "Mon salon",
    tzTitre2: "Suivez votre chiffre d'affaires",
    tzTexte2: "Consultez vos revenus et vos ventes en temps réel.",
    tzAlt2:
      "Un apercu du tableau de bord : le montant gagné sur la période, en évidence.",
    tzLabel3: "Fidélité",
    tzTitre3: "Récompensez leur fidélité",
    tzTexte3: "Du cashback automatique et un classement de vos clientes les plus fidèles.",
    tzAlt3:
      "Un apercu du programme de fidélité : les points cumulés par cliente et le classement des plus fidèles.",
    tzLabel4: "Pilotage",
    tzTitre4: "Gardez le contrôle",
    tzTexte4: "Visualisez facilement l'activité de votre salon.",
    tzAlt4:
      "Un apercu du suivi des commissions : le montant à payer et le montant déjà payé.",
    // Section sombre : le telephone n'est pas un simple relais du bureau,
    // c'est l'usage le plus frequent au comptoir — un point fort a part.
    mobEyebrow: "Toujours avec vous",
    mobH2a: "Votre caisse vous",
    mobH2b: "accompagne partout.",
    mobLede:
      "Au salon, chez vous ou en déplacement, gardez un œil sur votre activité quand vous en avez besoin.",
    mobAlt:
      "La caisse sur téléphone : la grille des services du salon et le panier, avec le bouton d'encaissement en bas de l'écran.",
    mobChip1Label: "Chiffre d'affaires",
    mobChip1Valeur: "420,000 TND",
    mobChip2Label: "Ventes du jour",
    mobChip2Valeur: "12 ventes",
    e3: "Ce qu'elle sait faire",
    h4a: "Six gestes du",
    h4b: "quotidien.",
    l1: "Encaissement",
    s1: "Encaissez en quelques secondes.",
    l2: "Agenda",
    s2: "Ne manquez plus jamais un rendez-vous.",
    l3: "Clientes",
    s3: "Connaissez mieux vos clientes.",
    l4: "Stock",
    s4: "Gardez votre stock sous contrôle.",
    l5: "Statistiques",
    s5: "Comprenez ce qui fait grandir votre salon.",
    // Ce 6e geste annoncait « Hors connexion ». La caisse a besoin
    // d'internet : l'historique des ventes le remplace, il existe vraiment.
    l6: "Historique",
    s6: "Retrouvez chaque vente, à la journée près.",
    e4: "La différence",
    h6a: "Le même salon,",
    h6b: "deux journées.",
    apres: "Avec Salonista",
    ap1: "Une caisse centralisée",
    ap2: "L'agenda dans la caisse",
    ap3: "Chaque cliente reconnue",
    ap4: "Le stock à jour tout seul",
    ap5: "Les chiffres du jour, en un coup d'œil",
    ap6: "Une gestion simplifiée",
    avant: "Avant Salonista",
    // Chaque ligne est ecrite pour repondre a son vis-a-vis (voir PAIRES dans
    // landing-client.tsx) : « des clientes qu'on ne reconnait pas » appelle
    // « chaque cliente reconnue », et ainsi de suite.
    av1: "Des ventes notées sur un cahier",
    av2: "Aucune visibilité sur la journée",
    av3: "Des rendez-vous dispersés",
    av4: "Un stock difficile à suivre",
    av5: "Des clientes qu'on ne reconnaît pas",
    av6: "Du temps perdu chaque soir",
    e5: "Pourquoi Salonista",
    h7a: "Pensé pour les salons.",
    h7b: "Conçu pour évoluer avec vous.",
    w1: "Simple à utiliser",
    w2: "Sans carte bancaire pour commencer",
    w3: "Prête en quelques minutes",
    w4: "Vos données au même endroit",
    w5: "Adaptée au marché tunisien",
    w6: "Interface moderne",
    w7: "Gestion centralisée",
    e6: "Questions",
    h8: "Ce qu'on nous demande",
    q1: "Il me faut quel matériel ?",
    a1: "Un ordinateur, une tablette ou un téléphone avec un navigateur récent, et une connexion internet. Une imprimante thermique 80 mm si vous voulez des tickets papier — sinon le ticket reste à l'écran.",
    // Remplace « Et si internet coupe ? », qui promettait un fonctionnement
    // hors connexion que la caisse n'assure pas.
    q2: "Est-ce que je peux essayer avant de m'engager ?",
    a2: "Oui. L'inscription est gratuite et ne demande aucune carte bancaire. Vous créez votre salon, vos services, et vous encaissez le jour même.",
    q3: "Mes employées verront-elles mon chiffre d'affaires ?",
    a3: "Seulement si vous le décidez. Chaque employée entre par son code, avec les droits que vous lui donnez.",
    q4: "Est-ce que ça restera gratuit ?",
    a4: "La caisse est gratuite aujourd'hui, sans limite de ventes. Les salons inscrits pendant cette phase gardent l'accès gratuit.",
    h9a: "Votre salon mérite mieux",
    h9b: "qu'une simple caisse.",
    p9: "Commencez gratuitement aujourd'hui.",
    cta3: "Démarrer ma caisse gratuitement",
    fine: "Aucune carte bancaire requise",
    foot: "Caisse pour salons de beauté · Tunisie",
    deja: "J'ai déjà un compte",
  },
  ar: {
  nav1: "الخدمات",
    nav2: "علاش سالونيستا",
    nav3: "الأثمنة",
    nav4: "أسئلة",
    cta: "ابدأ مجانا",
    cta2: "اكتشف سالونيستا",
    heroLede:
      "سيّر بيوعاتك، تابع رقم معاملاتك وابقى متحكّم في صالونك من التليفون، التابليت ولا الكمبيوتر متاعك.",
    altHero:
      "في كونتوار صالون، عاملة تورّي كاس سالونيستا في تابليت : خدمات الصالون بأثمنتها، والباني الحالي.",
    cta3: "ابدأ الكاس متاعي مجانا",
    eyebrow: "عرض الانطلاق · مجاني 100%",
    h1a: "الكاس الرقمية متاعك.",
    h1b: "صالونك.",
    h1c: "بكل بساطة.",
    b1: "كاس رقمية لصالونات التجميل",
    b2: "مجانية 100%",
    b3: "تليفون · تابليت · كمبيوتر",
    b4: "بيوعات وخدمات",
    e1: "الأساسي، مدروس مليح",
    h2a: "كاس مدروسة",
    h2b: "لصالونك.",
    h2lede:
      "سالونيستا كاس رقمية بسيطة، معمولة خصيصا لمحترفين التجميل.",
    tzLabel1: "الكاس",
    tzTitre1: "اخلّص بسهولة",
    tzTexte1: "سجّل بيوعاتك وخدماتك بسرعة.",
    tzAlt1: "جزء من شاشة الخلاص : خدمات الصالون وبداية الباني.",
    tzLabel2: "صالوني",
    tzTitre2: "تابع رقم معاملاتك",
    tzTexte2: "شوف مداخيلك وبيوعاتك في الوقت الحقيقي.",
    tzAlt2: "جزء من لوحة القيادة : المبلغ اللي ربحتو في الفترة، واضح.",
    tzLabel3: "الوفاء",
    tzTitre3: "كافئ وفاء حرفاءك",
    tzTexte3: "كاشباك آلي وترتيب لأكثر الحرفاء وفاء.",
    tzAlt3: "جزء من برنامج الوفاء : نقاط كل حرفاء وترتيب الأكثر وفاء.",
    tzLabel4: "التسيير",
    tzTitre4: "ابقى متحكّم",
    tzTexte4: "شوف بسهولة نشاط صالونك.",
    tzAlt4: "جزء من متابعة العمولات : المبلغ اللي يتخلّص والمبلغ اللي تخلّص.",
    mobEyebrow: "دايما معاك",
    mobH2a: "الكاس متاعك",
    mobH2b: "تلحقك في كل بلاصة.",
    mobLede:
      "في الصالون، في الدار ولا في الطريق، عين على نشاطك وقتلي تلزمك.",
    mobAlt:
      "الكاس في التليفون : خدمات الصالون والباني، وزر الخلاص في تحت الشاشة.",
    mobChip1Label: "رقم المعاملات",
    mobChip1Valeur: "420,000 دينار",
    mobChip2Label: "بيوعات النهار",
    mobChip2Valeur: "12 بيعة",
    e3: "شنوّة تنجم تعمل",
    h4a: "ستة حركات",
    h4b: "كل يوم.",
    l1: "الخلاص",
    s1: "خلّص في ثواني.",
    l2: "المواعيد",
    s2: "ما يفوتك حتى موعد.",
    l3: "الحرفاء",
    s3: "اعرف حرفاءك أكثر.",
    l4: "الستوك",
    s4: "ستوكك تحت عينك.",
    l5: "الإحصائيات",
    s5: "افهم شنوّة يكبّر صالونك.",
    l6: "تاريخ المبيعات",
    s6: "تلقى كل بيعة، نهار بنهار.",
    e4: "الفرق",
    h6a: "نفس الصالون،",
    h6b: "نهارين مختلفين.",
    avant: "قبل سالونيستا",
    av1: "مبيعات مكتوبة في كراس",
    av2: "ما تعرفش وين واصل في النهار",
    av3: "مواعيد مشتّتة",
    av4: "ستوك صعيب تتبّعو",
    av5: "حرفاء ما تعرفهمش",
    av6: "وقت ضايع كل ليلة",
    apres: "مع سالونيستا",
    ap1: "كاس مركزية",
    ap2: "المواعيد في الكاس",
    ap3: "كل حريفة معروفة",
    ap4: "الستوك يتحيّن وحدو",
    ap5: "أرقام النهار في نظرة",
    ap6: "تسيير مبسّط",
    e5: "علاش سالونيستا",
    h7a: "مصمّمة للصالونات.",
    h7b: "وتكبر معاك.",
    w1: "ساهلة للاستعمال",
    w2: "بلا كارط بنكية باش تبدا",
    w3: "جاهزة في دقايق",
    w4: "معطياتك في بلاصة وحدة",
    w5: "مناسبة للسوق التونسية",
    w6: "واجهة عصرية",
    w7: "تسيير مركزي",
    e6: "أسئلة",
    h8: "اللي يسألونا عليه",
    q1: "شنوّة يلزمني من معدات ؟",
    a1: "كمبيوتر، تابليت ولا تليفون بنافيغاتور جديد، وأنترنات. وطابعة حرارية 80 مم كان تحب تيكي بالورقة — وإلا التيكي يبقى في الشاشة.",
    q2: "نجم نجرّب قبل ما نلتزم ؟",
    a2: "إيه. التسجيل مجاني وما يلزمش كارط بنكية. تعمل صالونك، خدماتك، وتبدا تخلّص نفس النهار.",
    q3: "عاملاتي باش يشوفو رقم معاملاتي ؟",
    a3: "كان انت تحب برك. كل عاملة تدخل بالكود متاعها، بالحقوق اللي تعطيها انت.",
    q4: "باش تبقى مجانية ؟",
    a4: "الكاس مجانية اليوم، بلا حد للمبيعات. الصالونات اللي تسجّل في هالمرحلة تحافظ على المجانية.",
    h9a: "صالونك يستاهل أكثر",
    h9b: "من كاس عادية.",
    p9: "ابدأ مجانا اليوم.",
    fine: "بلا كارط بنكية",
    foot: "كاس لصالونات التجميل · تونس",
    deja: "عندي كونط",
  },
} as const;

export type Langue = keyof typeof CONTENU;
export type Textes = (typeof CONTENU)["fr"];
