/**
 * Textes de la page d'accueil, en francais et en arabe tunisien.
 *
 * Toute chaine affichee sur la landing vit ici : le composant ne contient
 * aucun texte en dur, ce qui permet de basculer la langue sans le toucher et
 * de relire la copie sans lire du JSX.
 */

export const CONTENU = {
  fr: {
  nav1: "Fonctionnalités",
    nav2: "Pourquoi Salonista",
    nav3: "Tarifs",
    nav4: "FAQ",
    cta: "Commencer gratuitement",
    eyebrow: "Caisse pour salons de beauté · Tunisie",
    h1a: "Le nouveau standard",
    h1b: "pour gérer votre salon.",
    cta2: "Découvrir Salonista",
    // Une seule phrase sous le titre : ce que fait le produit, pour qui.
    // NE PAS y remettre « sans internet » : la caisse en a besoin.
    heroLede:
      "Encaissez, gérez vos rendez-vous et suivez vos clientes depuis un téléphone, une tablette ou un ordinateur. Gratuit, sans engagement.",
    // Decrit la photo pour qui ne la voit pas : un lecteur d'ecran doit
    // apprendre ce que montre l'image, pas entendre « image ».
    altHero:
      "Une employée de salon, en tablier, consulte la caisse Salonista sur son téléphone, debout au comptoir de son salon.",
    hf1: "Aucune carte bancaire",
    hf2: "Prête en cinq minutes",
    hf3: "Sans engagement",
    e1: "La caisse",
    h2a: "Tout ce dont votre salon a besoin.",
    h2b: "Au même endroit.",
    c1: "Encaissement",
    c2: "Agenda",
    c3: "Clientes",
    c7: "Statistiques",
    // Les huit onglets, dans l'ordre du menu lateral de la caisse.
    ecSalon: "Mon salon",
    ecCaisse: "Caisse",
    ecRdv: "Rendez-vous",
    ecClientes: "Clientes",
    ecFidelite: "Fidélité",
    ecCommissions: "Commissions",
    ecProduits: "Produits",
    ecTiroir: "Tiroir",
    // Les fleches n'affichent qu'un chevron : sans ce libelle, un lecteur
    // d'ecran annoncerait « bouton ‹ ».
    ecranPrec: "Écran précédent",
    ecranSuiv: "Écran suivant",
    // Chaque capture est decrite : un lecteur d'ecran doit apprendre ce que
    // montre l'ecran, pas entendre huit fois « image ».
    altEcranSalon:
      "Le tableau de bord du salon : recette de la journée, clientes servies, panier moyen et service le plus demandé.",
    altEcranCaisse:
      "L'écran d'encaissement : la grille des services du salon à gauche, le panier et le bouton Encaisser à droite.",
    altEcranRdv:
      "L'agenda du jour : trois rendez-vous avec leur horaire et leur prestation, et le calendrier du mois à côté.",
    altEcranClientes:
      "La fiche des clientes : nombre de visites, total dépensé et solde de points de fidélité pour chacune.",
    altEcranFidelite:
      "Le programme de fidélité : réglage du cashback, portefeuilles des clientes et classement des plus fidèles.",
    altEcranCommissions:
      "Le suivi des commissions dues à l'équipe : taux de chaque employée, base de calcul et montant à payer.",
    altEcranProduits:
      "Le catalogue des produits : nom, référence, prix, stock restant et état de chaque article.",
    altEcranTiroir:
      "Le tiroir de caisse ouvert : fond de caisse, ventes en espèces, ventes par carte, pourboires et dépenses.",
    e3: "Ce qu'elle sait faire",
    h4a: "Six gestes du",
    h4b: "quotidien.",
    l1: "Encaissement",
    s1: "Encaissez en quelques secondes.",
    l2: "Agenda",
    s2: "Ne manquez plus jamais un rendez-vous.",
    l3: "Clientes",
    s3: "Connaissez mieux vos clientes.",
    l4: "Stock",
    s4: "Gardez votre stock sous contrôle.",
    l5: "Statistiques",
    s5: "Comprenez ce qui fait grandir votre salon.",
    // Ce 6e geste annoncait « Hors connexion ». La caisse a besoin
    // d'internet : l'historique des ventes le remplace, il existe vraiment.
    l6: "Historique",
    s6: "Retrouvez chaque vente, à la journée près.",
    e4: "La différence",
    h6a: "Le même salon,",
    h6b: "deux journées.",
    apres: "Avec Salonista",
    apresT: "Tout se tient.",
    ap1: "Une caisse centralisée",
    ap2: "L'agenda dans la caisse",
    ap3: "Chaque cliente reconnue",
    ap4: "Le stock à jour tout seul",
    ap5: "Les chiffres du jour, en un coup d'œil",
    ap6: "Une gestion simplifiée",
    avant: "Avant Salonista",
    avantT: "Tout est éparpillé.",
    av1: "Des cahiers",
    av2: "Des calculs à la main",
    av3: "Des rendez-vous dispersés",
    av4: "Un stock difficile à suivre",
    av5: "Aucune visibilité sur l'activité",
    av6: "Du temps perdu chaque soir",
    hint: "Faites glisser pour comparer",
    e5: "Pourquoi Salonista",
    h7a: "Pensé pour les salons.",
    h7b: "Conçu pour évoluer avec vous.",
    w1: "Simple à utiliser",
    w2: "Sans carte bancaire pour commencer",
    w3: "Prête en quelques minutes",
    w4: "Vos données au même endroit",
    w5: "Adaptée au marché tunisien",
    w6: "Interface moderne",
    w7: "Gestion centralisée",
    e6: "Questions",
    h8: "Ce qu'on nous demande",
    q1: "Il me faut quel matériel ?",
    a1: "Un ordinateur, une tablette ou un téléphone avec un navigateur récent, et une connexion internet. Une imprimante thermique 80 mm si vous voulez des tickets papier — sinon le ticket reste à l'écran.",
    // Remplace « Et si internet coupe ? », qui promettait un fonctionnement
    // hors connexion que la caisse n'assure pas.
    q2: "Est-ce que je peux essayer avant de m'engager ?",
    a2: "Oui. L'inscription est gratuite et ne demande aucune carte bancaire. Vous créez votre salon, vos services, et vous encaissez le jour même.",
    q3: "Mes employées verront-elles mon chiffre d'affaires ?",
    a3: "Seulement si vous le décidez. Chaque employée entre par son code, avec les droits que vous lui donnez.",
    q4: "Est-ce que ça restera gratuit ?",
    a4: "La caisse est gratuite aujourd'hui, sans limite de ventes. Les salons inscrits pendant cette phase gardent l'accès gratuit.",
    h9a: "Votre salon mérite mieux",
    h9b: "qu'une simple caisse.",
    p9: "Commencez gratuitement aujourd'hui.",
    cta3: "Démarrer ma caisse gratuitement",
    fine: "Aucune carte bancaire requise",
    foot: "Caisse pour salons de beauté · Tunisie",
    deja: "J'ai déjà un compte",
  },
  ar: {
  nav1: "الخدمات",
    nav2: "علاش سالونيستا",
    nav3: "الأثمنة",
    nav4: "أسئلة",
    cta: "ابدأ مجانا",
    cta2: "اكتشف سالونيستا",
    heroLede:
      "خلّص، سيّر مواعيدك وتابع حرفاءك من تليفون، تابليت ولا كمبيوتر. مجانا، وبلا التزام.",
    altHero:
      "عاملة في صالون، بالتابليي، تشوف كاس سالونيستا في تليفونها، واقفة في الكونتوار.",
    cta3: "ابدأ الكاس متاعي مجانا",
    eyebrow: "كاس لصالونات التجميل · تونس",
    h1a: "المعيار الجديد",
    h1b: "لتسيير صالونك.",
    hf1: "بلا كارط بنكية",
    hf2: "جاهزة في خمس دقايق",
    hf3: "بلا التزام",
    e1: "الكاس",
    h2a: "كل ما يلزم صالونك.",
    h2b: "في بلاصة وحدة.",
    c1: "الخلاص",
    c2: "المواعيد",
    c3: "الحرفاء",
    c7: "الإحصائيات",
    ecSalon: "صالوني",
    ecCaisse: "الكاس",
    ecRdv: "المواعيد",
    ecClientes: "الحرفاء",
    ecFidelite: "الوفاء",
    ecCommissions: "العمولات",
    ecProduits: "المنتوجات",
    ecTiroir: "التيروار",
    ecranPrec: "الشاشة السابقة",
    ecranSuiv: "الشاشة الموالية",
    altEcranSalon:
      "لوحة الصالون : مدخول النهار، عدد الحرفاء، معدل الباني والخدمة الأكثر طلبا.",
    altEcranCaisse:
      "شاشة الخلاص : خدمات الصالون على اليمين، والباني وزر الخلاص على اليسار.",
    altEcranRdv:
      "مواعيد النهار : ثلاثة مواعيد بالوقت والخدمة، وتقويم الشهر بجنبهم.",
    altEcranClientes:
      "بطاقة الحرفاء : عدد الزيارات، المبلغ المصروف ورصيد نقاط الوفاء لكل وحدة.",
    altEcranFidelite:
      "برنامج الوفاء : إعداد الكاشباك، محافظ الحرفاء وترتيب الأكثر وفاء.",
    altEcranCommissions:
      "متابعة العمولات متاع الفريق : نسبة كل عاملة، قاعدة الحساب والمبلغ اللي يتخلّص.",
    altEcranProduits:
      "قائمة المنتوجات : الاسم، المرجع، الثمن، الستوك الباقي وحالة كل منتوج.",
    altEcranTiroir:
      "التيروار محلول : فوند الكاس، مبيعات كاش، مبيعات كارط، البقشيش والمصاريف.",
    e3: "شنوّة تنجم تعمل",
    h4a: "ستة حركات",
    h4b: "كل يوم.",
    l1: "الخلاص",
    s1: "خلّص في ثواني.",
    l2: "المواعيد",
    s2: "ما يفوتك حتى موعد.",
    l3: "الحرفاء",
    s3: "اعرف حرفاءك أكثر.",
    l4: "الستوك",
    s4: "ستوكك تحت عينك.",
    l5: "الإحصائيات",
    s5: "افهم شنوّة يكبّر صالونك.",
    l6: "تاريخ المبيعات",
    s6: "تلقى كل بيعة، نهار بنهار.",
    e4: "الفرق",
    h6a: "نفس الصالون،",
    h6b: "نهارين مختلفين.",
    avant: "قبل سالونيستا",
    avantT: "كل شي مشتّت.",
    av1: "كراريس",
    av2: "حساب باليد",
    av3: "مواعيد مشتّتة",
    av4: "ستوك صعيب تتبّعو",
    av5: "ما تعرفش وين واصل",
    av6: "وقت ضايع كل ليلة",
    apres: "مع سالونيستا",
    apresT: "كل شي في بلاصتو.",
    ap1: "كاس مركزية",
    ap2: "المواعيد في الكاس",
    ap3: "كل حريفة معروفة",
    ap4: "الستوك يتحيّن وحدو",
    ap5: "أرقام النهار في نظرة",
    ap6: "تسيير مبسّط",
    hint: "جرّ باش تقارن",
    e5: "علاش سالونيستا",
    h7a: "مصمّمة للصالونات.",
    h7b: "وتكبر معاك.",
    w1: "ساهلة للاستعمال",
    w2: "بلا كارط بنكية باش تبدا",
    w3: "جاهزة في دقايق",
    w4: "معطياتك في بلاصة وحدة",
    w5: "مناسبة للسوق التونسية",
    w6: "واجهة عصرية",
    w7: "تسيير مركزي",
    e6: "أسئلة",
    h8: "اللي يسألونا عليه",
    q1: "شنوّة يلزمني من معدات ؟",
    a1: "كمبيوتر، تابليت ولا تليفون بنافيغاتور جديد، وأنترنات. وطابعة حرارية 80 مم كان تحب تيكي بالورقة — وإلا التيكي يبقى في الشاشة.",
    q2: "نجم نجرّب قبل ما نلتزم ؟",
    a2: "إيه. التسجيل مجاني وما يلزمش كارط بنكية. تعمل صالونك، خدماتك، وتبدا تخلّص نفس النهار.",
    q3: "عاملاتي باش يشوفو رقم معاملاتي ؟",
    a3: "كان انت تحب برك. كل عاملة تدخل بالكود متاعها، بالحقوق اللي تعطيها انت.",
    q4: "باش تبقى مجانية ؟",
    a4: "الكاس مجانية اليوم، بلا حد للمبيعات. الصالونات اللي تسجّل في هالمرحلة تحافظ على المجانية.",
    h9a: "صالونك يستاهل أكثر",
    h9b: "من كاس عادية.",
    p9: "ابدأ مجانا اليوم.",
    fine: "بلا كارط بنكية",
    foot: "كاس لصالونات التجميل · تونس",
    deja: "عندي كونط",
  },
} as const;

export type Langue = keyof typeof CONTENU;
export type Textes = (typeof CONTENU)["fr"];
